[workspace]
authors = ["Kasper Munch <kaspermunch@birc.au.dk>"]
channels = ["conda-forge"]
name = "PtDalgorithms"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
git = ">=2.49.0,<3"
conda-build = ">=25.4.2,<26"
conda-verify = ">=3.4.2,<4"
anaconda-client = ">=1.13.0,<2"
compilers = ">=1.9.0,<2"
