[workspace]
authors = ["Kasper Munch <kaspermunch@birc.au.dk>"]
channels = ["conda-forge"]
name = "PtDAlgorithms"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

[dependencies]
anaconda-client = ">=1.13.0,<2"
conda-build = ">=25.4.2,<26"
conda-verify = ">=3.4.2,<4"
r-base = ">=4.4.3,<4.5"
dlib = ">=19.24.2,<20"
