python:
  - 3.12
r_base:
  - 4.4

# numpy:
#   - 1.13

# python_cxx_compiler:
#   - gxx_linux-64
#   - clangxx_osx-64
#   - vs2019
# r_cxx_compiler:
#   - gxx_linux-64
#   - clangxx_osx-64
#   - m2w64-gcc
# target_platform:
#   - linux-64
#   - osx-64
#   - win-64

# zip_keys:
#   - python_cxx_compiler
#   - r_cxx_compiler
#   - target_platform
