

package:
  name: ptdalgorithms-base
  version: '0.19.96'

source:
  git_url: https://github.com/munch-group/ptdalgorithms.git

outputs:
    - name: ptdalgorithms
      requirements:
        build:
          - {{ compiler('c') }} 
          - {{ compiler('cxx') }} 
          - m2w64-toolchain    # [win]  
          # - compilers
          # - vc # [win]
          # - vs2019 # [win]          
          - python {{ python }}
          - git
          - cmake>=3.30
          - pybind11>=2.10.0
          - eigen
        host:
          - python {{ python }}
          - scikit-build-core
          - pybind11>=2.10.0
          - eigen
        run:
          - python {{ python }}
          - pybind11>=2.10.0
          - eigen    
          - numpy
          - python-graphviz
          - ipython
          - seaborn
      build:
        number: 1
        noarch: false
        script: '"$PYTHON" -m pip install . -vv' # [not win]
        script: '"%PYTHON%" -m pip install . -vv' # [win]

      channels:  # channels for your library dependencies
        - conda-forge
        # - defaults
      dependencies:   # Keep this block with only these two packages
        - anaconda-client
        - conda-build
        - conda-verify
        # - conda-package-handling
      test:
        imports:
          - ptdalgorithms
        # commands:
        #   - "$PYTHON -c 'import ptdalgorithms as ptd ; print(ptd.Graph(4).vertices_length() == 1)'" # [not win]
        #   - '"%PYTHON%" -c "import ptdalgorithms as ptd ; print(ptd.Graph(4).vertices_length() == 1)"' # [win]


    - name: r-ptdalgorithms
      requirements:
        build:
          - {{ compiler('c') }} 
          - {{ compiler('cxx') }}
          #- m2w64-toolchain    # [win]  
          # - compilers
          # - m2w64-gcc  # [win]
          # - vc # [win]
          # - vs2019 # [win]          
        #  - libcxx
          - r-base {{ r_base }}
          #- r-rcpp
          - m2w64-toolchain>=5.3.0,<6    # [win]
          #- r-base >=4.1.3,<4.2"
          - r-rcpp >=1.0.12,<2
        host:
          - r-base {{ r_base }}
          #- r-rcpp
          - r-rcpp>=1.0.12,<2
        run:
          - r-base {{ r_base }}
          #- r-rcpp
          - r-rcpp>=1.0.12,<2
          # - libgomp  # for OpenMP support
      build:
        number: 1
        noarch: false
        script: $R CMD INSTALL --build . # [not win]
        script: '"%R%" CMD INSTALL --build .' # [win]
      channels:  # channels for your library dependencies
        - conda-forge
        # - defaults

      dependencies:   # Keep this block with only these two packages
        #- anaconda-client
        #- conda-build
        #- conda-verify
        - conda-build>=25.4.2,<26
        - conda-verify>=3.4.2,<4
        - anaconda-client>=1.13.0,<2


      test:
        imports:
          - ptdalgorithms
        # commands:
        #   - "$R -e 'library('ptdalgorithms') ; print(vertices_length(create_graph(4)) == 1)'" # [not win]
        #   - "%R% -e 'library('ptdalgorithms') ; print(vertices_length(create_graph(4)) == 1)'" # [win]

about:
  home: https://github.com/munch-group/ptdalgorithms.git
  license: MIT
  dev_url: https://github.com/munch-group/ptdalgorithms.git
  doc_url: https://munch-group.org/ptdalgorithms
