{% set pyproject = load_file_data("../pyproject.toml", from_recipe_dir=True) %}

package:
  name: ptdalgorithms
  version: {{ pyproject.get("project").get("version") }}
  # version: {{ data.get('version') }}  

source:
  git_url: https://github.com/munch-group/ptdalgorithms.git


build:
  number: 0
  skip: true # [py<310]
  # script: "$PYTHON -m pip install . -vv"

  # run_exports:
  #   strong:
  #     - {{ compiler('cxx') }}

requirements:
  host:
    - python

outputs:
  - name: ptdalgorithms
    script: build_base.bat  # [win]
    script: build_base.sh  # [not win]
    build:
      ignore_run_exports_from:
        - zlib  
    requirements:
      build:
        - python                                 # [build_platform != target_platform]
        - cross-python_{{ target_platform }}     # [build_platform != target_platform]
        - numpy                                  # [build_platform != target_platform]
        - pybind11 >=2.13.2,!=2.13.3             # [build_platform != target_platform]
        - eigen >= 3.3                           # [build_platform != target_platform]
        - {{ stdlib('c') }}
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - cmake >= 3.30                          # [win]
        - pkg-config
        - libtool                                # [unix]
        - ninja
        - git
      host:
        - python
        - pip
        - scikit-build-core
        - pybind11 >= 2.13.2,!=2.13.3
        - eigen
        - numpy
      run:
        - python
        - numpy
        - graphviz
        - ipython
        - seaborn

  # build:
  #   - {{ compiler('cxx') }}
  #   # - python
  #   # - pip
  #   - git
  #   - cmake>=3.5
  #   - pybind11>=2.10.0
  #   - eigen
  # host:
  #   - python
  #   # - pip
  #   - scikit-build-core
  #   - pybind11>=2.10.0
  #   - eigen
  # run:
  #   # - python
  #   - numpy
  #   - graphviz
  #   - ipython
  #   - seaborn

  # build:
  #   - {{ compiler('cxx') }}
  #   - git
  #   - cmake>=3.5
  #   # - ninja
  # host:
  #   - python
  #   - make                        
  #   - scikit-build-core
  #   - pybind11>=2.10.0
  #   - eigen
  # run:
  #   - python
  #   - numpy
  #   - graphviz
  #   - ipython
  #   - seaborn

    # {% for dep in pyproject.get("project").get("dependencies") %}
    # - {{ dep.lower() }}
    # {% endfor %}

channels:  # channels for your library dependencies
  - conda-forge
  - default

dependencies:   # Keep this block with only these two packages
  - anaconda-client
  - conda-build
  - conda-verify

test:
  imports:
    - ptdalgorithms

about:
  home: https://github.com/munch-group/ptdalgorithms.git
  license: MIT
  dev_url: https://github.com/munch-group/ptdalgorithms.git
  doc_url: https://munch-group.org/ptdalgorithms
