{% set pyproject = load_file_data("../pyproject.toml", from_recipe_dir=True) %}

package:
  name: ptdalgorithms
  version: {{ pyproject.get("project").get("version") }}
  # version: {{ data.get('version') }}  

source:
  git_url: https://github.com/munch-group/ptdalgorithms.git


build:
  number: 1
  script: "$PYTHON -m pip install . -vv"

  # run_exports:
  #   strong:
  #     - {{ stdlib('c') }}
  #     - {{ compiler('c') }}
  #     - {{ compiler('cxx') }}
  #     - pybind11>=2.10.0
  #     - eigen
  #     - libstdc++
  # #     - libgomp

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}    
    - python {{ python }}
    # - pip
    - git
    - cmake>=3.30
    - libstdc++
    - pybind11>=2.10.0
    - eigen
  host:
    - python {{ python }}
    # - pip
    - scikit-build-core
    - pybind11>=2.10.0
    - eigen
  run:
    - python {{ python }}
    - pybind11>=2.10.0
    - eigen    
    - numpy
    - graphviz
    - ipython
    - seaborn

  # build:
  #   - {{ compiler('cxx') }}
  #   - git
  #   - cmake>=3.5
  #   # - ninja
  # host:
  #   - python
  #   - make                        
  #   - scikit-build-core
  #   - pybind11>=2.10.0
  #   - eigen
  # run:
  #   - python
  #   - numpy
  #   - graphviz
  #   - ipython
  #   - seaborn

    # {% for dep in pyproject.get("project").get("dependencies") %}
    # - {{ dep.lower() }}
    # {% endfor %}

channels:  # channels for your library dependencies
  - conda-forge
  - default

dependencies:   # Keep this block with only these two packages
  - anaconda-client
  - conda-build
  - conda-verify

test:
  imports:
    - ptdalgorithms

about:
  home: https://github.com/munch-group/ptdalgorithms.git
  license: MIT
  dev_url: https://github.com/munch-group/ptdalgorithms.git
  doc_url: https://munch-group.org/ptdalgorithms
