

package:
  name: ptdalgorithms-base
  version: '0.20.0'

source:
  git_url: https://github.com/munch-group/ptdalgorithms.git

outputs:
    - name: ptdalgorithms
      requirements:
        build:
          - {{ compiler('c') }}
          - {{ compiler('cxx') }}
          - python #{{ python }}
          - cmake>=3.30
          - ninja
          - pybind11>=2.10.0
          - eigen
        host:
          - python #{{ python }}
          - scikit-build-core
          - pybind11>=2.10.0
          - eigen
        run:
          - python #{{ python }}
          - pybind11>=2.10.0
          - eigen
          - numpy
          - python-graphviz
          - ipython
          - seaborn
          - tqdm
        run_constrained:
          # Optional JAX support for gradient-based inference
          # These are not required but if installed must meet these version constraints
          - jax >=0.4.0
          - jaxlib >=0.4.0
          - equinox
      build:
        number: 1
        noarch: false
        script: |
          # set CMAKE_GENERATOR=
          ninja --version || where ninja || echo "Ninja not found!"
          "$PYTHON" -m pip install . -vv   # [not win]
          "%PYTHON%" -m pip install . -vv  # [win]

      channels:  # channels for your library dependencies
        - conda-forge
        # - defaults
      dependencies:   # Keep this block with only these two packages
        - anaconda-client
        - conda-build
        - conda-verify
        # - conda-package-handling
      test:
        imports:
          - ptdalgorithms
        # commands:
        #   - "$PYTHON -c 'import ptdalgorithms as ptd ; print(ptd.Graph(4).vertices_length() == 1)'" # [not win]
        #   - '"%PYTHON%" -c "import ptdalgorithms as ptd ; print(ptd.Graph(4).vertices_length() == 1)"' # [win]


    # - name: r-ptdalgorithms
    #   requirements:
    #     build:
    #       - {{ compiler('c') }} 
    #       - {{ compiler('cxx') }}
    #       - cmake>=3.30
    #       - ninja
    #       - r-base #{{ r_base }}
    #       - r-rcpp
    #     host:
    #       - r-base #{{ r_base }}
    #       - r-rcpp
    #     run:
    #       - r-base #{{ r_base }}
    #       - r-rcpp
    #       # - libgomp  # for OpenMP support
    #   build:
    #     number: 1
    #     noarch: false
    #     script: |
    #       set CMAKE_GENERATOR=
    #       ninja --version || where ninja || echo "Ninja not found!"
    #       $R CMD INSTALL --build . # [not win]
    #       "%R%" CMD INSTALL --build . # [win]
    #   channels:  # channels for your library dependencies
    #     - conda-forge
    #     # - defaults

    #   test:
    #     commands:
    #       - $R -e "library('ptdalgorithms')"  # [not win]
    #       - "%R% -e \"library('ptdalgorithms')\""  # [win]
    #     # commands:
    #     #   - "$R -e 'library('ptdalgorithms') ; print(vertices_length(create_graph(4)) == 1)'" # [not win]
    #     #   - "%R% -e 'library('ptdalgorithms') ; print(vertices_length(create_graph(4)) == 1)'" # [win]

about:
  home: https://github.com/munch-group/ptdalgorithms.git
  license: MIT
  dev_url: https://github.com/munch-group/ptdalgorithms.git
  doc_url: https://munch-group.org/ptdalgorithms
