{% set pyproject = load_file_data("../pyproject.toml", from_recipe_dir=True) %}

package:
  name: ptdalgorithms
  version: {{ pyproject.get("project").get("version") }}
  # version: {{ data.get('version') }}  

source:
  git_url: https://github.com/munch-group/ptdalgorithms.git

build:
  number: 0
  script: "python -m pip install . -vv"
  # script: "{{ PYTHON }} -m pip install . -vv"
  # script: "$PYTHON -m pip install . -vv"
  # script_env:
  #   - CFLAGS=-I${PREFIX}/include/eigen3"
  # entry_points:
  #   - exercises = exercise_client:launch_exercise

requirements:
  build:
    - {{ compiler('cxx') }}
    - setuptools>=77.0.3
    - pybind11>=2.10.0
    - eigen

  host:
    - python
    - pip
  run:  # your library dependencies
    {% for dep in pyproject.get("project").get("dependencies") %}
    - {{ dep.lower() }}
    {% endfor %}
    # - python
    # - graphviz
    # # - python-graphviz
    # - ipython
    # - pybind11>=2.10.0
    # - eigen

channels:  # channels for your library dependencies
  # - uibcdf
  - conda-forge
  - default

dependencies:   # Keep this block with only these two packages
  - anaconda-client
  - conda-build=24 # from 25 the output file is a .conda not .tar.bz2
  - conda-verify
  # - setuptools>=42
  # - pybind11>=2.10.0
  # - eigen

test:
  imports:
    - ptdalgorithms

about:
  home: https://github.com/munch-group/ptdalgorithms.git
  license: MIT
  dev_url: https://github.com/munch-group/ptdalgorithms.git
  doc_url: https://munch-group.org/ptdalgorithms
