{% set pyproject = load_file_data("../pyproject.toml", from_recipe_dir=True) %}

package:
  name: ptdalgorithms
  version: '0.19.47'

source:
  git_url: https://github.com/munch-group/ptdalgorithms.git

outputs:
    - name: ptdalgorithms
#      version: {{ pyproject.get("project").get("version") }}
      requirements:
        build:
          - {{ compiler('cxx') }}  
          - python {{ python }} # pin to specified version
          - git
          - cmake>=3.30
          - pybind11>=2.10.0
          - eigen
        host:
          - python {{ python }}
          - scikit-build-core
          - pybind11>=2.10.0
          - eigen
        run:
          - python {{ python }}
          - pybind11>=2.10.0
          - eigen    
          - numpy
          - python-graphviz
          - ipython
          - seaborn
      build:
        number: 1
        script: "$PYTHON -m pip install . -vv"
      channels:  # channels for your library dependencies
        - conda-forge
        - default
      dependencies:   # Keep this block with only these two packages
        - anaconda-client
        - conda-build
        - conda-verify
        - conda-package-handling
      test:
        imports:
          - ptdalgorithms
        commands:
          - $PYTHON -e "import ptdalgorithms as ptd ; print(ptd.Graph(4).vertices_length() == 1)"


    - name: r-ptdalgorithms
#      version: {{ pyproject.get("project").get("version") }}
      requirements:
        build:
          - {{ compiler('cxx') }}
          - libcxx
          - r-base {{ r_base }}
          - r-rcpp
        host:
          - r-base {{ r_base }}
          - r-rcpp
        run:
          - r-base {{ r_base }}
          - r-rcpp
          # - libgomp  # for OpenMP support
      build:
        noarch: false
        script: $R CMD INSTALL --build .
          # tar xvfz ptdalgorithms_{{ pyproject.get("project").get("version") }}.tgz
          # tar cfvj ptdalgorithms_{{ pyproject.get("project").get("version") }}.tar.bz2 ptdalgorithms
      channels:  # channels for your library dependencies
        - conda-forge
        - default

      dependencies:   # Keep this block with only these two packages
        - anaconda-client
        - conda-build
        - conda-verify
        - conda-package-handling
      test:
        imports:
          - ptdalgorithms
        commands:
          - $R -e "library('ptdalgorithms') ; print(vertices_length(create_graph(4)) == 1)"

about:
  home: https://github.com/munch-group/ptdalgorithms.git
  license: MIT
  dev_url: https://github.com/munch-group/ptdalgorithms.git
  doc_url: https://munch-group.org/ptdalgorithms
