{% set pyproject = load_file_data("../pyproject.toml", from_recipe_dir=True) %}

package:
  name: ptdalgorithms
  version: {{ pyproject.get("project").get("version") }}

source:
  git_url: https://github.com/munch-group/ptdalgorithms.git

build:
  number: 1
  script: "$PYTHON -m pip install . -vv"

requirements:
  build:
    - {{ compiler('cxx') }}  
    - python {{ python }} # pin to specified version
    - git
    - cmake>=3.30
    - pybind11>=2.10.0
    - eigen
  host:
    - python {{ python }}
    - scikit-build-core
    - pybind11>=2.10.0
    - eigen
  run:
    - python {{ python }}
    - pybind11>=2.10.0
    - eigen    
    - numpy
    - python-graphviz
    - ipython
    - seaborn

channels:  # channels for your library dependencies
  - conda-forge
  - default

dependencies:   # Keep this block with only these two packages
  - anaconda-client
  - conda-build
  - conda-verify

test:
  imports:
    - ptdalgorithms

about:
  home: https://github.com/munch-group/ptdalgorithms.git
  license: MIT
  dev_url: https://github.com/munch-group/ptdalgorithms.git
  doc_url: https://munch-group.org/ptdalgorithms
