

package:
  name: ptdalgorithms-base
  version: '0.19.79'

source:
  git_url: https://github.com/munch-group/ptdalgorithms.git

outputs:
    - name: ptdalgorithms
      requirements:
        build:
          - {{ compiler('cxx') }}  
          - python {{ python }}
          - git
          - cmake>=3.30
          - pybind11>=2.10.0
          - eigen
        host:
          - python {{ python }}
          - scikit-build-core
          - pybind11>=2.10.0
          - eigen
        run:
          - python {{ python }}
          - pybind11>=2.10.0
          - eigen    
          - numpy
          - python-graphviz
          - ipython
          - seaborn
      build:
        number: 1
        noarch: false
        script: '"$PYTHON" -m pip install . -vv' # [not win]
        script: '"%PYTHON%" -m pip install . -vv' # [win]

      channels:  # channels for your library dependencies
        - conda-forge
        - default
      dependencies:   # Keep this block with only these two packages
        - anaconda-client
        - conda-build
        - conda-verify
        - conda-package-handling
      test:
        imports:
          - ptdalgorithms
        # commands:
        #   - "$PYTHON -c 'import ptdalgorithms as ptd ; print(ptd.Graph(4).vertices_length() == 1)'" # [not win]
        #   - '"%PYTHON%" -c "import ptdalgorithms as ptd ; print(ptd.Graph(4).vertices_length() == 1)"' # [win]


    - name: r-ptdalgorithms
      requirements:
        build:
          - {{ compiler('cxx') }}
        #  - libcxx
          - r-base {{ r_base }}
          - r-rcpp
          - rtools
        host:
          - r-base {{ r_base }}
          - r-rcpp
        run:
          - r-base {{ r_base }}
          - r-rcpp
          # - libgomp  # for OpenMP support
      build:
        number: 1
        noarch: false
        script: $R CMD INSTALL --build . # [not win]
        script: '"%R%" CMD INSTALL --build .' # [win]
      channels:  # channels for your library dependencies
        - conda-forge
        - default

      dependencies:   # Keep this block with only these two packages
        - anaconda-client
        - conda-build
        - conda-verify
        - conda-package-handling
      test:
        imports:
          - ptdalgorithms
        # commands:
        #   - "$R -e 'library('ptdalgorithms') ; print(vertices_length(create_graph(4)) == 1)'" # [not win]
        #   - "%R% -e 'library('ptdalgorithms') ; print(vertices_length(create_graph(4)) == 1)'" # [win]

about:
  home: https://github.com/munch-group/ptdalgorithms.git
  license: MIT
  dev_url: https://github.com/munch-group/ptdalgorithms.git
  doc_url: https://munch-group.org/ptdalgorithms
