project:
  type: website
  output-dir: _build
  # resources:
  # - objects.txt
  # - objects-test.txt

execute:
  freeze: auto
  echo: true

metadata-files:
  - api/_sidebar.yml

filters:
  - "interlinks"

interlinks:
  fast: true
  sources:
    python:
      url: https://docs.python.org/3/
    griffe:
      url: https://mkdocstrings.github.io/griffe/
    numpy:
      url: https://numpy.org/doc/stable/
    pandas:
      url: https://pandas.pydata.org/docs/
    matplotlib:
      url: https://matplotlib.org/stable/
    scipy:
      url: https://docs.scipy.org/doc/scipy/
    statsmodels:
      url: https://www.statsmodels.org/stable/      
    # quartodoc-test:
    #   url: https://machow.github.io/quartodoc
    #   inv: objects-test.txt

website:
  title: "ptdalgorithms"
  page-navigation: true
  navbar:
    left:
      - href: api/
        text: Python API reference
      - href: r_api/
        text: R API reference
      - href: c_api/
        text: C API reference
      # - file: examples/
      #   text: Examples
    right:
      - icon: github
        href: https://github.com/munch-group/ptdalgorithms/
  sidebar:
    - id: pages
      title: Get Started
      style: floating
      align: left
      contents:
        - pages/getting_started.qmd
        - section: "Basics"
          contents:
            - pages/state_space.ipynb
            - pages/moments.ipynb
            - pages/distributions.ipynb
            - pages/laplace.ipynb
        - section: "Advanced"
          contents:
            - pages/state_lumping.ipynb
            - pages/epochs.ipynb
            - pages/joint_prob.ipynb
        - section: "Distributed Computing"
          contents:
            - pages/distributed_computing_basics.ipynb
            - pages/distributed_svgd_inference.ipynb
            - pages/slurm_cluster_setup.ipynb
            - pages/architecture.qmd
            - pages/auto_parallel_computing.ipynb
            - pages/cpu_monitoring_showcase.ipynb
            - pages/distributed_computing_basics.ipynb
            - pages/distributed_computing.qmd
            - pages/distributed_svgd_inference.ipynb
            - pages/graphbuilder_showcase.ipynb
            - pages/math_and_algorithms.qmd
            - pages/phase-type-distributions.qmd
            - pages/slurm_multinode_guide.qmd
            - pages/svgd_inference.ipynb
        - section: "Examples"
          contents:
            - examples/python/rabbits_full_py_api_example.ipynb
            - examples/python/coalescent-jointprob.ipynb
            - examples/python/experiments.ipynb
            - examples/python/isolation_migration.ipynb
            - examples/python/getting_started.ipynb
            - examples/python/somecode.ipynb
            - examples/python/laplace.ipynb
            - examples/python/two-island-two-locus-arg.ipynb
            # - pages/

lightbox: true

format:
  html:
#    theme: cosmo
    css:
      - api/_styles-quartodoc.css
      # - styles.css

      - numpy-navbar-sidebar.css
      - styles.css  # for code highlighting styles
    theme: 
      light: [cosmo, custom.scss]
      dark: [darkly, custom-dark.scss]    


    toc: true
    mermaid:
      theme: neutral     

quartodoc:
  package: ptdalgorithms
  # package: null
  # source_dir: ../src/cpp
  style: pkgdown
  dir: api
  dynamic: true  # Use runtime import for compiled extensions
  parser: numpy  # Use numpy docstring parser (more lenient)
  render_interlinks: true
  options:
    signature_name: full
    include_inherited: true
    include_empty: false  # Skip items that can't be loaded
  renderer:
    style: markdown
    table_style: description-list
  sidebar: "api/_sidebar.yml"
  css: "api/_styles-quartodoc.css"
  sections:
    - title: Graph Construction
      package: ptdalgorithms
      desc: |
        Graph components (Vertex and Edge are documented as part of Graph)
      contents:
        - Graph
    - title: JAX-compatible utils
      package: ptdalgorithms
      desc: |
        JAX-compatible phase-type distribution computations with FFI integration.
        Supports JIT compilation, automatic differentiation, and vmap/pmap parallelization.
      contents:
        - compute_pmf_ffi
        - compute_moments_ffi
        - compute_pmf_and_moments_ffi
    - title: Inference
      package: ptdalgorithms
      desc: |
        SVGD
      contents:
        - SVGD
    - title: Distributed Computing
      package: ptdalgorithms
      desc: |
        Multi-node distributed computing utilities for SLURM clusters.
        Simplifies scaling from single machine to 100+ nodes with automatic
        JAX distributed initialization and configuration management.
      contents:
        # - subtitle: "Distributed Initialization"
        #   desc: "Auto-detection and setup for multi-node computing"
        - DistributedConfig
        - initialize_distributed
        - detect_slurm_environment
        - get_coordinator_address
        - configure_jax_devices
        - initialize_jax_distributed
        # - subtitle: "Cluster Configuration"
        #   desc: "YAML-based cluster configuration management"
        - ClusterConfig
        - load_config
        - get_default_config
        - validate_config
        - suggest_config


    # - title: Some other section
    #   package: ptdalgorithms
    #   desc: |
    #     Some description...
    #   contents:
    #     - scriptname


# quartodoc:
#   package: genominterv
#   style: pkgdown
#   dir: api
#   render_interlinks: true
#   options:
#     signature_name: full
#   renderer:
#     style: markdown
#     table_style: description-list
#   sidebar: "api/_sidebar.yml"
#   css: "api/_styles-quartodoc.css"

#   sections:
#     - title: Genomic set operations
#       package: genominterv
#       desc: |
#         Set operations on pandas.DataFrames with columns for chromosome, start, and end.
#       contents:
#         - interval_diff     
#         - interval_union   
#         - interval_intersect 
#         - interval_collapse
#     - title: Remapping
#       package: genominterv.remapping
#       desc: |
#         Mapping intervals relative to other coordinates.
#       contents:        
#         - interval_distance
#         - remap_interval_data
#     - title: Statistics
#       package: genominterv.stats
#       desc: Mapping intervals relative to other coordinates.
#       contents:
#         - proximity_test        
#         - jaccard_stat
#     - title: Decorators
#       package: genominterv.decorators
#       desc: |
#         Utilities for user created genomic intervals and bootstrap tests.
#       contents:
#         - genomic 
#         - bootstrap
#     - title: Interval set utilities
#       package: genominterv.interval_set_op
#       desc: |
#         Set operations on sorted lists of (start, end) tuples.
#       contents:
#         - union 
#         - diff
#         - invert
#         - intersect
#         - collapse
#     - title: Interval mapping utilities
#       package: genominterv.remapping
#       desc: |
#         Set operations on sorted lists of (start, end) tuples.
#       contents:
#         - remap 
